# ==============================
# Configuración Base de Datos
# ==============================
#spring.datasource.url=jdbc:mysql://${DB_HOST:${SPRING_DATASOURCE_HOST:localhost}}:${DB_PORT:${SPRING_DATASOURCE_PORT:3306}}/${DB_NAME:${SPRING_DATASOURCE_DB:api_aprendiz}}
#spring.datasource.username=${DB_USER:${SPRING_DATASOURCE_USERNAME:root}}
#spring.datasource.password=${DB_PASSWORD:${SPRING_DATASOURCE_PASSWORD:}}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.datasource.url = jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
# ==============================
# Configuración Hibernate / JPA
# ==============================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# ==============================
# Swagger
# ==============================
springdoc.swagger-ui.path=/swagger-ui-custom.html
